# Generated by Django 4.2.4 on 2023-08-22 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_room_options_rename_create_room_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='create',
            new_name='created',
        ),
    ]
